### ISSUE TITLE
3.14 project does not run

### ISSUE THREAD

**Issue by fluffur** [ggelashvili/learnphptherightway-project#39]
Project does not run with provided `docker-compose.yml` configuration

```

➜  docker git:(3.14) docker compose up --build -d
[+] Building 0.0s (0/0)                                                                                                                        docker:default
please specify build context (e.g. "." for the current directory)

```

I tried to  change `programwithgio-app` container build configuration, but it did not work (scheduler does not run script anyway)

**Comment by ivandez** [comment]
You have to run "docker compose up --build -d" inside docker directory.

In my case when I downloaded the project, vscode opened the project in this path

"/learnphptherightway-project/"

So I wrote "cd docker" to change directory, then the path is

"/learnphptherightway-project/docker"

Finally, I run  "docker compose up --build -d" and eveything will work perfectly

**Comment by ggelashvili** [comment]
Let me know if you still have an issue. Thank you @ivandez
